name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - run: chmod +x ./gradlew
      - run: ./gradlew build --stacktrace